### ISSUE TITLE
IP好像被封了，找的代理IP为什么都运行不了嘞

### ISSUE THREAD

**Issue by smxcbql** [fengx1a0/Bilibili_show_ticket_auto_order#62]

**Comment by fengx1a0** [comment]
协议+IP+代理

**Comment by smxcbql** [comment]
意思是只修改proxies值是运行不了的是吗

**Comment by fengx1a0** [comment]
> 意思是只修改proxies值是运行不了的是吗

http代理可以，我用的是http代理(v2)，配置如下
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/74698099/eb198e46-cdc1-4412-b49f-a013a871e2da)

**Comment by smxcbql** [comment]
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/134673647/c99e4785-39cd-4e3a-a214-2275f4004bef)
按照设置之后

**Comment by smxcbql** [comment]
网上也找过几个免费的IP但都跑不起来，换成none就是一直获取token我看它错误信息如“慢一点”“555票没了”这种都没输出过

**Comment by fengx1a0** [comment]
> 网上也找过几个免费的IP但都跑不起来，换成none就是一直获取token我看它错误信息如“慢一点”“555票没了”这种都没输出过

免费的IP指的是什么，http代理服务器一般会开放一个代理端口，你的免费IP代理端口都配置对了吗

**Comment by smxcbql** [comment]
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/134673647/b9aecd47-fd53-49e7-ade6-72959f888340)
这种类似，是我找错了吗

**Comment by fengx1a0** [comment]
> ![image](https://user-images.githubusercontent.com/134673647/253709242-b9aecd47-fd53-49e7-ade6-72959f888340.png) 这种类似，是我找错了吗

这是http代理吗

**Comment by smxcbql** [comment]
我也不知道哎，http://www.66ip.cn/areaindex_11/1.html这是它的网址，您看看？

**Comment by fengx1a0** [comment]
我试过了，这个站上的免费代理基本不能用

**Comment by smxcbql** [comment]
好吧好吧哎，谢谢佬

**Comment by smxcbql** [comment]
请问应该去哪找可以用的HTTP代理

**Comment by zjutcaicai** [comment]
佬，之前给你打了五十。我想请教一下，你的proxies中，127.0.0.1是本机地址吧，是定死的吗？端口号是代理ip的端口号吗，我用的是v2rayN梯子，开启http代理和全局模式就可以了吧。






World&nbsp;class&nbsp;in&nbsp;a&nbsp;single
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fengx1a0/Bilibili_show_ticket_auto_order"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月15日(星期六) 上午9:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [fengx1a0/Bilibili_show_ticket_auto_order] IP好像被封了，找的代理IP为什么都运行不了嘞 (Issue #62)





  
意思是只修改proxies值是运行不了的是吗
  
http代理可以，我用的是http代理(v2)，配置如下

**Comment by fengx1a0** [comment]
> 佬，之前给你打了五十。我想请教一下，你的proxies中，127.0.0.1是本机地址吧，是定死的吗？端口号是代理ip的端口号吗，我用的是v2rayN梯子，开启http代理和全局模式就可以了吧。 World&nbsp;class&nbsp;in&nbsp;a&nbsp;single ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fengx1a0/Bilibili_show_ticket_auto_order" ***@***.***&gt;; 发送时间:&nbsp;2023年7月15日(星期六) 上午9:39 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [fengx1a0/Bilibili_show_ticket_auto_order] IP好像被封了，找的代理IP为什么都运行不了嘞 (Issue #62) 意思是只修改proxies值是运行不了的是吗 http代理可以，我用的是http代理(v2)，配置如下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

v2ray可以的看这里
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/74698099/c89027d0-4a3e-49a3-a8b5-086fe2b8543c)
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/74698099/a6411b86-e08a-4143-a3e3-6443ce19ba7f)
或者是这
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/74698099/8dc8e5cc-30ea-4c92-9851-3ce9076cb000)
如果和我一样你的地址就是127.0.0.1:10809

**Comment by zjutcaicai** [comment]
确实，我也发现了是这个。但我的节点显示速度明明在7、8M/s,为什么响应速度这么慢呢，我设置的sleep时间间隔在0.4,但却很慢。是B站对外网的响应速度做了限制吗，还是我该用其他地区，目前用了台湾的都比较慢。




World&nbsp;class&nbsp;in&nbsp;a&nbsp;single
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fengx1a0/Bilibili_show_ticket_auto_order"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月15日(星期六) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fengx1a0/Bilibili_show_ticket_auto_order] IP好像被封了，找的代理IP为什么都运行不了嘞 (Issue #62)





  
佬，之前给你打了五十。我想请教一下，你的proxies中，127.0.0.1是本机地址吧，是定死的吗？端口号是代理ip的端口号吗，我用的是v2rayN梯子，开启http代理和全局模式就可以了吧。 World&nbsp;class&nbsp;in&nbsp;a&nbsp;single @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fengx1a0/Bilibili_show_ticket_auto_order" @.&gt;; 发送时间:&nbsp;2023年7月15日(星期六) 上午9:39 @.&gt;; @.&gt;; 主题:&nbsp;Re: [fengx1a0/Bilibili_show_ticket_auto_order] IP好像被封了，找的代理IP为什么都运行不了嘞 (Issue #62) 意思是只修改proxies值是运行不了的是吗 http代理可以，我用的是http代理(v2)，配置如下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are su

 如果和我一样你的地址就是127.0.0.1:10809

**Comment by fengx1a0** [comment]
> 确实，我也发现了是这个。但我的节点显示速度明明在7、8M/s,为什么响应速度这么慢呢，我设置的sleep时间间隔在0.4,但却很慢。是B站对外网的响应速度做了限制吗，还是我该用其他地区，目前用了台湾的都比较慢。 World&nbsp;class&nbsp;in&nbsp;a&nbsp;single ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fengx1a0/Bilibili_show_ticket_auto_order" ***@***.***&gt;; 发送时间:&nbsp;2023年7月15日(星期六) 上午10:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [fengx1a0/Bilibili_show_ticket_auto_order] IP好像被封了，找的代理IP为什么都运行不了嘞 (Issue #62) 佬，之前给你打了五十。我想请教一下，你的proxies中，127.0.0.1是本机地址吧，是定死的吗？端口号是代理ip的端口号吗，我用的是v2rayN梯子，开启http代理和全局模式就可以了吧。 World&nbsp;class&nbsp;in&nbsp;a&nbsp;single @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fengx1a0/Bilibili_show_ticket_auto_order" @.&gt;; 发送时间:&nbsp;2023年7月15日(星期六) 上午9:39 @.&gt;; @.&gt;; 主题:&nbsp;Re: [fengx1a0/Bilibili_show_ticket_auto_order] IP好像被封了，找的代理IP为什么都运行不了嘞 (Issue #62) 意思是只修改proxies值是运行不了的是吗 http代理可以，我用的是http代理(v2)，配置如下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are su 如果和我一样你的地址就是127.0.0.1:10809 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

如果不是你节点ping的问题，那就是叔叔有地域歧视，节点看下载速度没用
